In [2]:
import numpy as np

def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    A = np.random.random([n,1])
    
    return A
    
    raise NotImplementedError

In [4]:
randomization(5)

array([[0.66210615],
       [0.17886173],
       [0.25989736],
       [0.96402986],
       [0.29183545]])

In [6]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.random([h,w])
    B = np.random.random([h,w])
    s = A + B
    
    return A, B, s  
    
    raise NotImplementedError


In [7]:
operations(2,3)

(array([[0.57283039, 0.23219492, 0.21924973],
        [0.32569212, 0.23081725, 0.49833571]]),
 array([[0.31367023, 0.76121861, 0.0443407 ],
        [0.62472037, 0.3895262 , 0.28174056]]),
 array([[0.88650062, 0.99341353, 0.26359043],
        [0.95041249, 0.62034345, 0.78007627]]))

In [8]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    t = A + B
    s = np.linalg.norm(t)
    
    return s
        
    raise NotImplementedError

In [11]:
norm([1,2,3], [2,3,5])

7.211102550927978

In [107]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    
    weights_trans = np.array(np.transpose(weights))
    t = np.matmul(weights_trans, inputs)
    out = np.array(np.tanh(t))
    
    return out
    
    raise NotImplementedError

In [108]:
neural_network([[1],[1]], [[1],[2]])

array([[0.99505475]])

In [110]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if x <= y:
        z = x*y
    else:
        z = x/y
    return z
    
    raise NotImplementedError

In [120]:
scalar_function(3,2)

1.5

In [124]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    vk = np.vectorize(scalar_function)
    
    
    return(vk(x, y))
    
    
    raise NotImplementedError


In [126]:
vector_function([3],[2])

array([1.5])

In [273]:
def get_sum_metrics(predictions, metrics=[]): 
    for i in range(3):
        metrics.append(lambda x, i=i: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)
    
    metrics.clear()
    return sum_metrics

In [275]:
print(get_sum_metrics(3, [lambda x: x]))

15


In [276]:
print(get_sum_metrics(0)) 

3


In [1]:
## https://docs.python-guide.org/writing/gotchas/
