In [169]:
def get_order(n_samples):
    try:
        with open(str(n_samples) + '.txt') as fp:
            line = fp.readline()
            return list(map(int, line.split(',')))
    except FileNotFoundError:
        random.seed(1)
        indices = list(range(n_samples))
        random.shuffle(indices)
        return indices

In [ ]:
from string import punctuation, digits
import numpy as np
import random

def hinge_loss_single(feature_vector, label, theta, theta_0):
    """
    Finds the hinge loss on a single data point given specific classification
    parameters.

    Args:
        feature_vector - A numpy array describing the given data point.
        label - A real valued number, the correct classification of the data
            point.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given data point and parameters.
    """
    
    feature_vector_trans = np.array(np.transpose(feature_vector))
    t = np.matmul(feature_vector_trans, theta)
    z = label*(t+theta_0)
    
    if z >= 1:
        loss = 0
    else:
        loss = 1 - z
    return loss
    
    raise NotImplementedError

In [36]:
hinge_loss_single([1, 2], -1, [-1, 1], 2)

4

In [102]:
def hinge_loss_full(feature_matrix, labels, theta, theta_0):
    """
    Finds the total hinge loss on a set of data given specific classification
    parameters.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given dataset and parameters. This number should be the average hinge
    loss across all of the points in the feature matrix.
    """
    
    loss_sum = 0
    
    for i in range(len(np.array(feature_matrix))):
        loss_sum = loss_sum + hinge_loss_single(feature_matrix[i], labels[i], theta, theta_0)

    loss_avg = loss_sum/(i+1)
    
    
    return loss_avg


    raise NotImplementedError

In [103]:
hinge_loss_full([[1, 2], [1, 1]], [-1, 1], [-1, 1], 2)

2.0

In [240]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the perceptron algorithm.

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        current_theta - The current theta being used by the perceptron
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the perceptron
            algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    
    feature_vector_trans = np.array(np.transpose(feature_vector))
    t = np.matmul(feature_vector_trans, current_theta)
    z = label*(t + current_theta_0)
    
    if z < 0.0001:
        new_theta = np.sum([current_theta, label*feature_vector], axis=0)
        new_theta_0 = current_theta_0 + label
    else:
        new_theta = current_theta
        new_theta_0 = current_theta_0
    
    thethas = (new_theta, new_theta_0)
    
    return thethas
    
    raise NotImplementedError

In [244]:
perceptron_single_step_update([1, 2], 1, [-1, 1], -1.5)

(array([0, 3]), -0.5)

In [264]:
def perceptron(feature_matrix, labels, T):
    """
    Runs the full perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])

    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    theta, the linear classification parameter, after T iterations through the
    feature matrix and the second element is a real number with the value of
    theta_0, the offset classification parameter, after T iterations through
    the feature matrix.
    """
    thethas_1 = np.zeros(len(feature_matrix[0])) #initializing thethas_1+ to 0
    thetha_0 = 0 #initializing thethas to 0
    thethas = (thethas_1, thetha_0)
    
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            thethas = perceptron_single_step_update(feature_matrix[i], labels[i], thethas[0], thethas[1])
            pass
        
    return thethas
    
    raise NotImplementedError

In [265]:
perceptron(np.array([[1, 2]]), np.array([1]), 2)

(array([1., 2.]), 1)

In [266]:
feature_matrix = np.array([[0, 1, 2], [2,3,3]])
print(len(feature_matrix[0]))

for i in get_order(feature_matrix.shape[0]):
    print(feature_matrix[i])
    print(i)
    
thethas_1 = np.zeros(len(feature_matrix[0])) #initializing thethas to 0
print(thethas_1)
thetha_0 = 0 #initializing thethas to 0
thethas = (thethas_1, thetha_0)
print(thethas)
print(thethas[1])

3
[2 3 3]
1
[0 1 2]
0
[0. 0. 0.]
(array([0., 0., 0.]), 0)
0


In [281]:
def average_perceptron(feature_matrix, labels, T):
    """
    Runs the average perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])


    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    the average theta, the linear classification parameter, found after T
    iterations through the feature matrix and the second element is a real
    number with the value of the average theta_0, the offset classification
    parameter, found after T iterations through the feature matrix.

    Hint: It is difficult to keep a running average; however, it is simple to
    find a sum and divide.
    """
    
    thethas_1 = np.zeros(len(feature_matrix[0])) #initializing thethas_1+ to 0
    thetha_0 = 0 #initializing thethas to 0
    thethas = (thethas_1, thetha_0)

    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            thethas = perceptron_single_step_update(feature_matrix[i], labels[i], thethas[0], thethas[1])
            thethas_1 = np.sum([thethas_1, thethas[0]], axis=0)
            thetha_0 = thetha_0 + thethas[1]
            pass
    
    thethas_final = (thethas_1/(T*feature_matrix.shape[0]), thetha_0/(T*feature_matrix.shape[0])) 
    return thethas_final
    
    raise NotImplementedError

In [283]:
average_perceptron(np.array([[1, 2],[-1,0]]), np.array([1, 1]), 2)

(array([-0.25,  1.5 ]), 1.75)

In [285]:
def pegasos_single_step_update(
        feature_vector,
        label,
        L,
        eta,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the Pegasos algorithm

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        L - The lamba value being used to update the parameters.
        eta - Learning rate to update parameters.
        current_theta - The current theta being used by the Pegasos
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the
            Pegasos algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    
    feature_vector_trans = np.array(np.transpose(feature_vector))
    t = np.matmul(feature_vector_trans, current_theta)
    z = label*(t + current_theta_0)
    
    if z <= 1:
        new_theta = np.sum([(1-L*eta)*current_theta, eta*label*feature_vector], axis=0)
        new_theta_0 = current_theta_0 + eta*label
    else:
        new_theta = (1-L*eta)*current_theta
        new_theta_0 = current_theta_0
    
    thethas = (new_theta, new_theta_0)
    
    return thethas
    
    
    
    raise NotImplementedError

In [291]:
pegasos_single_step_update(
        np.array([1, 1]),
        1,
        0.2,
        0.1,
        np.array([-1,1]),
        1)

(array([-0.88,  1.08]), 1.1)

In [316]:
def pegasos(feature_matrix, labels, T, L):
    """
    Runs the Pegasos algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    For each update, set learning rate = 1/sqrt(t),
    where t is a counter for the number of updates performed so far (between 1
    and nT inclusive).

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the algorithm
            should iterate through the feature matrix.
        L - The lamba value being used to update the Pegasos
            algorithm parameters.

    Returns: A tuple where the first element is a numpy array with the value of
    the theta, the linear classification parameter, found after T
    iterations through the feature matrix and the second element is a real
    number with the value of the theta_0, the offset classification
    parameter, found after T iterations through the feature matrix.
    """
    
    thethas_1 = np.zeros(len(feature_matrix[0])) #initializing thethas_1+ to 0
    thetha_0 = 0 #initializing thethas to 0
    thethas = (thethas_1, thetha_0)
    counter = 1
    
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):            
            eta = 1/(counter)**0.5
            thethas = pegasos_single_step_update(feature_matrix[i], labels[i], L, eta, thethas[0], thethas[1])
            counter = counter + 1
            pass
    
    return thethas
    
    
    
    raise NotImplementedError

In [317]:
pegasos(np.array([[1, 2]]), np.array([1]), 1, 0.2)

(array([1., 2.]), 1.0)